name       : boomaga
version    : 0.9.1
release    : 6
source     :
    - https://github.com/Boomaga/boomaga/archive/v0.9.1.tar.gz : e09548f5938d391ee85d044aec8871b93ff9c912b05932af3c2a1efaf83473ea
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.core
summary    : Boomaga (BOOklet MAnager) is a virtual printer for viewing a document
    before printing it out using the physical printer
description: |
    Boomaga (BOOklet MAnager) is a virtual printer for viewing a document before printing it out using the physical printer
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Help)
    - cups-devel
    - snappy-devel
setup      : |
    %patch -p1 < $pkgfiles/poppler-0.58.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
