name       : boomaga
version    : 1.3.0
release    : 9
source     :
    - https://github.com/Boomaga/boomaga/archive/v1.3.0.tar.gz : fd05be1100701cf6e7bbbf41b635ca2ca4d1eaf88bfdcf4a83f9a6ba8de24e35
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.core
summary    : Boomaga (BOOklet MAnager) is a virtual printer for viewing a document before printing it out using the physical printer
description: |
    Boomaga (BOOklet MAnager) is a virtual printer for viewing a document before printing it out using the physical printer
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Help)
    - cups-devel
    - snappy-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
