name       : boomaga
version    : 3.0.0
release    : 14
source     :
    - https://github.com/Boomaga/boomaga/archive/v3.0.0.tar.gz : 74af10ec5a78008d335011eca0f63ed7ccd4bc2fdac2f4cffa73db7acc05e767
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.core
summary    : Boomaga (BOOklet MAnager) is a virtual printer for viewing a document before printing it out using the physical printer
description: |
    Boomaga (BOOklet MAnager) is a virtual printer for viewing a document before printing it out using the physical printer
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Help)
    - cups-devel
    - snappy-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
