name       : boomaga
version    : 0.8.0
release    : 2
source     :
    - https://github.com/Boomaga/boomaga/archive/v0.8.0.tar.gz : 88c1eb6730bc9f54103c86a767020574ccd7ef1fb0aa08bf120786a41b984f90
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.core
summary    : Boomaga (BOOklet MAnager) is a virtual printer for viewing a document
    before printing it out using the physical printer
description: |
    Boomaga (BOOklet MAnager) is a virtual printer for viewing a document before printing it out using the physical printer
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - cups-devel
    - snappy-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
